apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: consumer-scaledobject-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: service-bus-connection-secret
    key: ServiceBusAzure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 15 # Default: 30 seconds
  cooldownPeriod: 300 # Default 300 seconds
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: keda-poc-ns
      queueName: keda-poc-queue
      messageCount: "10"
    authenticationRef:
      name: consumer-scaledobject-auth
