kind: Namespace
apiVersion: v1
metadata:
  name: poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: jailtonjunior/consumer:v1
        resources:
          requests:
            cpu: 15m
            memory: "32Mi"
          limits:
            cpu: 30m
            memory: "64Mi"
