apiVersion: v1
kind: Secret
metadata:
  name: service-bus-connection-secret
data:
  ServiceBusAzure: RW5kcG9pbnQ9c2I6Ly9rZWRhLXBvYy1ucy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PXdXSkFpdWlaNld6aXpSb3RGVHl0Q3lVVW9UZTRaTkczdGM3a2htMWtsWHc9
